//Login
export const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS'
export const LOGIN_ERROR: string = 'LOGIN_ERROR'
export const LOGIN_REQUEST: string = 'LOGIN_REQUEST'
export const LOGIN_TRY_AGAIN: string = 'LOGIN_TRY_AGAIN'
export const LOGIN_LOADING: string = 'LOGIN_LOADING'
export const SET_DATA_CONFIG: string = 'SET_DATA_CONFIG'
export const LOGOFF: string = 'LOGOFF'

//Token
export const SET_TOKEN_AS_VALID = 'SET_TOKEN_AS_VALID'
export const SET_TOKEN_AS_INVALID = 'SET_TOKEN_AS_INVALID'
export const CHECK_IF_IS_VALID_TOKEN = 'CHECK_IF_IS_VALID_TOKEN'
export const CLEAR_AUTH: string = 'CLEAR_AUTH'

//Question
export const UPDATE_QUESTION_SCORE: string = 'UPDATE_QUESTION_SCORE'

//Form
export const CLIENT_SET: string = 'CLIENT_SET'
export const CLIENT_UNSET: string = 'CLIENT_UNSET'
export const RESET_FORM: string = 'RESET_FORM'

//Foto
export const DELETE_IMAGE_GALERIA: string = 'DELETE_IMAGE_GALERIA'
export const UPDATE_IMAGE_GALERIA_APP: string = 'UPDATE_IMAGE_GALERIA_APP'
export const UPDATE_IMAGE_GALERIA_DESk: string = 'UPDATE_IMAGE_GALERIA_DESK'
export const PHOTOS_CREATE_SUCCESS: string = 'PHOTOS_CREATE_SUCCESS'
export const PHOTOS_CREATE_ERROR: string = 'PHOTOS_CREATE_ERROR'
export const PHOTOS_CREATE_REQUEST: string = 'PHOTOS_CREATE_REQUEST'
export const DELETE_PHOTO_REQUEST_APP: string = 'DELETE_PHOTO_REQUEST_APP'
export const DELETE_PHOTO_REQUEST_DESK: string = 'DELETE_PHOTO_REQUEST_DESK'
export const DELETE_PHOTO_ERROR: string = 'DELETE_PHOTO_ERROR'
export const MODAL_PHOTO: string = 'MODAL_PHOTO'
export const GALERY_PHOTO: string = 'GALERY_PHOTO'
export const LISTPHOTOS_CREATE_SUCCESS: string = 'LISTPHOTOS_CREATE_SUCCESS'
export const LISTPHOTOS_CREATE_ERROR: string = 'LISTPHOTOS_CREATE_ERROR'
export const LISTPHOTOS_CREATE_REQUEST: string = 'LISTPHOTOS_CREATE_REQUEST'

//Gallery
export const GALLERY_CREATE_SUCCESS: string = 'GALLERY_CREATE_SUCCESS'
export const GALLERY_CREATE_ERROR: string = 'GALLERY_CREATE_ERROR'
export const GALLERY_CREATE_REQUEST: string = 'GALLERY_CREATE_REQUEST'

//GET CLAIM
export const VERIFY_TOKEN_REQUEST: string = 'VERIFY_TOKEN_REQUEST'
export const VERIFY_TOKEN_SUCCESS: string = 'VERIFY_TOKEN_SUCCESS'
export const VERIFY_TOKEN_ERROR: string = 'VERIFY_TOKEN_ERROR'
export const NOT_VERIFY_TOKEN: string = 'NOT_VERIFY_TOKEN'
export const CLEAR_DATA: string = 'CLEAR_DATA'

//CATEGORY
export const GET_CATEGORY_REQUEST: string = 'GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS: string = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_ERROR: string = 'GET_CATEGORY_ERROR'

// CATEGORY BY ID
export const GET_CATEGORY_BI_ID_REQUEST: string = 'GET_CATEGORY_BI_ID_REQUEST'
export const GET_CATEGORY_BI_ID_SUCCESS: string = 'GET_CATEGORY_BI_ID_SUCCESS'
export const GET_CATEGORY_BI_ID_ERROR: string = 'GET_CATEGORY_BI_ID_ERROR'
export const CLEAR_CATEGORY_BI_ID: string = 'CLEAR_CATEGORY_BI_ID'

//Send Claim
export const SEND_CLAIM_REQUEST: string = 'SEND_CLAIM_REQUEST'
export const SEND_CLAIM_SUCCESS: string = 'SEND_CLAIM_SUCCESS'
export const INITIAL_REQUESTING = 'INITIAL_REQUESTING'
export const SEND_CLAIM_ERROR: string = 'SEND_CLAIM_ERROR'
export const CHANGED_STEP: string = 'CHANGED_STEP'

//CLAIM
export const UPDATE_CLAIM_REQUEST: string = 'UPDATE_CLAIM_REQUEST'
export const UPDATE_CLAIM_SUCCESS: string = 'UPDATE_CLAIM_SUCCESS'
export const UPDATE_CLAIM_ERROR: string = 'UPDATE_CLAIM_ERROR'

export const FINALIZE_CLAIM_REQUEST: string = 'FINALIZE_CLAIM_REQUEST'
export const FINALIZE_CLAIM_SUCCESS: string = 'FINALIZE_CLAIM_SUCCESS'
export const FINALIZE_CLAIM_ERROR: string = 'FINALIZE_CLAIM_ERROR'

//ANSWER
export const SEND_ANSWER_REQUEST: string = 'SEND_ANSWER_REQUEST'
export const SEND_ANSWER_SUCCESS: string = 'SEND_ANSWER_SUCCESS'
export const SEND_ANSWER_ERROR: string = 'SEND_ANSWER_ERROR'
//Company
export const GET_COMPANY_REQUEST: string = 'GET_COMPANY_REQUEST'
export const GET_COMPANY_SUCCESS: string = 'GET_COMPANY_SUCCESS'
export const GET_COMPANY_ERROR: string = 'GET_COMPANY_ERROR'

//Locations
export const GET_LOCATIONS_REQUEST: string = 'GET_LOCATIONS_REQUEST'
export const GET_LOCATIONS_SUCCESS: string = 'GET_LOCATIONS_SUCCESS'
export const GET_LOCATIONS_ERROR: string = 'GET_LOCATIONS_ERROR'

//CONFIG
export const GET_CONFIG_REQUEST: string = 'GET_CONFIG_REQUEST'
export const GET_CONFIG_SUCCESS: string = 'GET_CONFIG_SUCCESS'
export const GET_CONFIG_ERROR: string = 'GET_CONFIG_ERROR'

//PROVIDERS
export const GET_PROVIDERS_REQUEST: string = 'GET_PROVIDERS_REQUEST'
export const GET_PROVIDERS_SUCCES: string = 'GET_PROVIDERS_SUCCESS'
export const GET_PROVIDERS_ERROR: string = 'GET_PROVIDERS_ERROR'

export const UPDATE_PROVIDERS_REQUEST: string = 'UPDATE_PROVIDERS_REQUEST'
export const UPDATE_PROVIDERS_SUCCESS: string = 'UPDATE_PROVIDERS_SUCCESS'
export const UPDATE_PROVIDERS_ERROR: string = 'UPDATE_PROVIDERS_ERROR'

export const SET_PROVIDERS_REQUEST: string = 'SET_PROVIDERS_REQUEST'
export const SET_PROVIDERS_SUCCESS: string = 'SET_PROVIDERS_SUCCESS'
export const SET_PROVIDERS_ERROR: string = 'SET_PROVIDERS_ERROR'

//COLLABORATORS
export const GET_COLLABORATORS_REQUEST: string = 'GET_COLLABORATORS_REQUEST'
export const GET_COLLABORATORS_SUCCESS: string = 'GET_COLLABORATORS_SUCCESS'
export const GET_COLLABORATORS_ERROR: string = 'GET_COLLABORATORS_ERROR'

export const UPDATE_COLLABORATORS_REQUEST: string = 'UPDATE_COLLABORATORS_REQUEST'
export const UPDATE_COLLABORATORS_SUCCESS: string = 'UPDATE_COLLABORATORS_SUCCESS'
export const UPDATE_COLLABORATORS_ERROR: string = 'UPDATE_COLLABORATORS_ERROR'

export const SET_COLLABORATORS_REQUEST: string = 'SET_COLLABORATORS_REQUEST'
export const SET_COLLABORATORS_SUCCESS: string = 'SET_COLLABORATORS_SUCCESS'
export const SET_COLLABORATORS_ERROR: string = 'SET_COLLABORATORS_ERROR'








